# SPDX-FileCopyrightText: 2023 Rivos Inc.
#
# SPDX-License-Identifier: Apache-2.0

image: "rust:latest"

default:
  before_script:
    - rustc --version
    - cargo --version

stages:
  - test

build-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - cargo build

lint-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - rustup component add clippy
    - cargo clippy -- -D warnings  -Wmissing-docs

format-code:
  stage: test
  script:
    - rustup target add riscv64gc-unknown-none-elf
    - rustup component add rustfmt
    - cargo fmt -- --check --config format_code_in_doc_comments=true

test-code:
  stage: test
  script:
    - cargo test --target x86_64-unknown-linux-gnu --workspace --exclude test_workloads --lib
